codepalace/CodePalaceBase/urls.py
from django.urls import path
from . import views

app_name = "CodePalaceBase"

urlpatterns = [
    path('', views.home, name="home"),

    # CRUD operations
    path('questions/', views.QuestionListView.as_view(), name="questions_list"),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(),
         name="questions_detail"),

    path('questions/create', views.QuestionCreateView.as_view(),
         name="question_create"),

    path('questions/<int:pk>/update', views.QuestionUpdateView.as_view(),
         name="question_update"),

    path('questions/<int:pk>/delete', views.QuestionDeleteView.as_view(),
         name="question_delete"),
    path('questions/<int:pk>/comment', views.AddCommentView.as_view(),
         name="question_comment"),

    # added
    path('profile/<int:pk>/', views.ProfileDetailView.as_view(),
         name="profiles"),

]

codepalace/codepalace/urls.py
from django.contrib import admin
from django.urls import path, include
from CodePalaceUsers import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CodePalaceBase.urls')),


    # Auth
    path('register/', user_views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="codepalaceUsers/login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(
        template_name="codepalaceUsers/logout.html"), name="logout"),


    # profile

    path("profile/", user_views.profile, name="profile"),
    path("profile/update/", user_views.profile_update, name="profile_update"),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

codepalace/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Code Palace</title>
    <link rel="shortcut icon" href="https://d29fhpw069ctt2.cloudfront.net/icon/image/37726/preview.svg">
    <link rel="apple-touch-icon" href="https://d29fhpw069ctt2.cloudfront.net/icon/image/37726/preview.svg">
    <link rel="image_src" href="https://d29fhpw069ctt2.cloudfront.net/icon/image/37726/preview.svg">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
        integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
        crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css' %}">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
<style>
    .message-animate {
    animation: slideInFromTop 0.5s ease-in-out forwards;
}

@keyframes slideInFromTop {
    0% {
        transform: translateY(-100%);
    }
    100% {
        transform: translateY(0);
    }
}
</style>
</head>

<body>

    <header>

        <div class="nav-container">
            <nav>
                <div class="nav-brand">
                    <div class="hamburger-menu-container">

                        <div class="hamburger-menu">
                            <div class="line"></div>
                            <div class="line"></div>
                            <div class="line"></div>
                        </div>
                       
                    </div>

                    <a href="{% url 'CodePalaceBase:home' %}" class="nav-icon">
                        <img class="logo" src="{% static "download.svg" %}">
                        <a href="{% url 'CodePalaceBase:home' %}" style="text-decoration: none; color: black;">
                            <div class="nav-icon-text">code <span class="nav-bold-text">palace</span>
                        </a>


                </div>
                </a>
        </div>
        <div class="nav-base-links">
            <ul>
                <li><a href="#">About us</a></li>
                <li><a href="#">Items</a></li>
                <li><a href="#">Terms&Conditions</a></li>
            </ul>
        </div>
        <div class="nav-search">
            <div class="search-container">
                <i class="fas fa-search"></i>
                <form action="" method="GET">
                    <input type="text" id="searchbar" name="search-area" placeholder="Search...">
                    <button type="submit"
                        style="margin-left: 340px; border-radius: 25px; border: none; padding: 8px;">Search</button>
                </form>
            </div>
            <div class="search-hints">
                <div class="search-arrow-up"></div>
                <div class="search-hint-body">
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>[tag] </span> search within a tag</div>
                        <div class="hint-text"><span>user:1234 </span> search by author</div>
                        <div class="hint-text"><span>"words here"</span> exact phrase </div>
                    </div>
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>answers:0</span> unanswered questions</div>
                        <div class="hint-text"><span> score:3 </span> posts with a 3+ score</div>
                    </div>
                </div>
                <div class="search-hint-footer">
                    <a href="#" class="btn">Ask a question</a>
                    <a href="#" class="search-help">Search help</a>
                </div>
            </div>

        </div>
        <div class="nav-right-buttons">
            <div class="search-btn">
                <i class="fas fa-search"></i>
            </div>
            
                    {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}" class="btn btn-login">Profile</a>
                    <a href="{% url 'logout' %}" class="btn btn-register">Logout</a>
                    {% else %}
                    <a href="{% url 'login' %}" class="btn btn-login">Login</a>
                    <a href="{% url 'register' %}" class="btn btn-register">Sign up</a>
                    {% endif %}
                </div>
                </nav>
                </div>
                    <div style="margin-top: 10px;" class="message-home">
                        {% if messages %}
                        {% for message in messages %}
                        <div id="message-alert" class="alert alert-{{ message.tags }} message-animate" role="alert">
                            <h4 style="text-align: center;">{{ message }}</h4>
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>

    </header>

 

    {% block content %}

    {% endblock content %}

       <script src="{% static 'main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"
        integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js"
        integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/"
        crossorigin="anonymous"></script>
        <script>
            setTimeout(() => {
                const messageAlert = document.getElementById('message-alert');
                messageAlert.parentNode.removeChild(messageAlert);
            }, 3000);
        </script>
       
</body>

</html>

codepalace/templates/home.html
{% extends 'base.html' %} {% block content %}
<section class="hero">
  <div class="hero-content">
    <h1 class="hero-title">
      Coding <span>dreams</span> come true at Code Palace
    </h1>
    <p class="hero-paragraph">Building Knowledge Brick by Brick : )</p>
    <div class="hero-options">
      <a href="#" class="btn btn-developers" style="margin: 6rem 0 0 0"
        >Why Code-Palace?</a
      >

      <a href=" {% url 'CodePalaceBase:questions_list' %} " class="btn btn-developers" style="margin: 6rem 0 0 3rem"
        >Latest Questions</a
      >
    </div>
  </div>
</section>

<section class="for-developers">
  <div class="container">
    <div class="section-head">
      <h2 class="section-title">Power of unity</h2>
      <div class="section-line"></div>
      <p class="section-description">
        Anyone who codes is welcome to join the community at Code Palace. We assist you in finding your next dream job, getting solutions to your most challenging coding queries, and privately sharing information with your colleagues.
      </p>
    </div>
    <div class="options">
   
      <div class="option">
        <div class="option-icon">
          <img
            src="https://static.vecteezy.com/system/resources/previews/022/359/434/original/3d-frequently-asked-questions-icon-illustration-render-png.png"
            alt="Private Q & A"
          />
        </div>
        <div class="option-title">Public Q&A</div>
        <div class="option-description">
          As you work, advance with Code Palace. Use our industry-leading Q&A engine to discreetly share expertise with your colleagues.
        </div>
        <div class="option-button">
        </div>
      </div>
      <div class="option">
        <div class="option-icon">
          <img
            src="https://static.vecteezy.com/system/resources/previews/022/359/434/original/3d-frequently-asked-questions-icon-illustration-render-png.png"
            alt="Private Q & A"
          />
        </div>
        <div class="option-title">Ask us!</div>
        <div class="option-description">
          As you work, advance with Code Palace. Use our industry-leading Q&A engine to discreetly share expertise with your colleagues.
        </div>
        <div class="option-button">
        </div>
      </div>
      <div class="option">
        <div class="option-icon">
          <img
            src="https://static.vecteezy.com/system/resources/previews/022/359/434/original/3d-frequently-asked-questions-icon-illustration-render-png.png"
            alt="Private Q & A"
          />
        </div>
        <div class="option-title">Public Q&A</div>
        <div class="option-description">
          As you work, advance with Code Palace. Use our industry-leading Q&A engine to discreetly share expertise with your colleagues.
        </div>
        <div class="option-button">
        </div>
      </div>
      
    </div>
  </div>
</section>

<section class="for-businesses">
  <div class="container">
    <div class="section-head">
      <h2 class="section-title"> Heaven for Coders </h2>
      <div class="section-line"></div>
      <p class="section-description">
        Our goal is to assist developers in writing the future's screenplay. This entails assisting you in locating and hiring qualified developers for your company and giving them the resources they require in order to collaborate and perform well.
      </p>
    </div>

    <div class="options">
      <div class="option">
        <div class="option-icon">
          <img
            src="https://cdn.sstatic.net/Img/home/private-questions.svg?v=a4f1cfb08f7e"
            alt="Private Q&A"
          />
        </div>
        <div class="option-description">
         Find Answers Quickly
          <a href="#" class="option-link">Private Q&A</a>
        </div>
      </div>
      <div class="option">
        <div class="option-icon">
          <img
            src="https://cdn.sstatic.net/Img/home/find-candidate.svg?v=9099aa106ad3"
            alt="Talent solutions"
          />
        </div>
        <div class="option-description">
          As per your need
          <a href="#" class="option-link">Any Time</a>
        </div>
      </div>
      <div class="option">
        <div class="option-icon">
          <img
            src="https://cdn.sstatic.net/Img/home/accelerate.svg?v=9d4c2786ff02"
            alt=" Advertising platform"
          />
        </div>
        <div class="option-description">
          Just Google it :)
          <a href="#" class="option-link">Happy Coding</a>
        </div>
      </div>
    </div>
  </div>
</section>



{% endblock content %}

codepalace/templates/profile.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    <script src="https://unpkg.com/feather-icons"></script>
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap"
      rel="stylesheet"
    />

    <style>
      body {
        background-color: #ffff;
        /* background: linear-gradient(230deg, orange 0%, yellow 100%); */
      }

      .padding {
        padding-top: 6rem !important;
      }

      .user-card-full {
        overflow: hidden;
      }

      .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
        border: none;
        margin-bottom: 30px;
      }

      .m-r-0 {
        margin-right: 0px;
      }

      .m-l-0 {
        margin-left: 0px;
      }

      .user-card-full .user-profile {
        border-radius: 5px 0 0 5px;
      }

      .bg-c-lite-green {
        background: -webkit-gradient(
          linear,
          left top,
          right top,
          from(#f29263),
          to(#ee5a6f)
        );
        background: linear-gradient(to right, rgb(255, 208, 0), orange);
      }

      .user-profile {
        padding: 20px 0;
      }

      .card-block {
        padding: 1.25rem;
      }

      .m-b-25 {
        margin-bottom: 25px;
      }

      .img-radius {
        border-radius: 100px;
      }
      @media only screen and (min-width: 1400px) {
        .img-radius {
          border-radius: 100px;
        }
      }
      h6 {
        font-size: 13px;
        font-family: "Poppins", sans-serif;
      }

      .card .card-block p {
        line-height: 25px;
      }

      @media only screen and (min-width: 1400px) {
        p {
          font-size: 14px;
        }
      }

      .card-block {
        padding: 1.25rem;
      }

      .b-b-default {
        border-bottom: 1px solid #e0e0e0;
      }

      .m-b-20 {
        margin-bottom: 20px;
      }

      .p-b-5 {
        padding-bottom: 5px !important;
      }

      .card .card-block p {
        line-height: 25px;
      }

      .m-b-10 {
        margin-bottom: 10px;
      }

      .text-muted {
        color: #919aa3 !important;
      }

      .b-b-default {
        border-bottom: 1px solid #e0e0e0;
      }

      .f-w-600 {
        font-weight: 600;
      }

      .m-b-20 {
        margin-bottom: 20px;
      }

      .m-t-40 {
        margin-top: 20px;
      }

      .p-b-5 {
        padding-bottom: 5px !important;
      }

      .m-b-10 {
        margin-bottom: 10px;
      }

      .m-t-40 {
        margin-top: 20px;
      }

      .user-card-full .social-link li {
        display: inline-block;
      }

      .user-card-full .social-link li a {
        font-size: 20px;
        margin: 0 10px 0 0;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
    </style>
  </head>
  <body>
    <div class="page-content page-container" id="page-content">
      <div class="padding">
        <div class="row d-flex justify-content-center">
          <div class="col-xl-6 col-md-12">
            <div class="card user-card-full">
              <div class="row m-l-0 m-r-0">
                <div class="col-sm-4 bg-c-lite-green user-profile">
                  <div class="card-block text-center text-white">
                    <div class="m-b-25">
                      <img
                        style="height: 12rem; width: 12rem"
                        src="{{user.profile.image.url}}"
                        class="img-radius"
                        alt="User-Profile-Image"
                      />
                    </div>
                    <h6 class="f-w-600" style="font-size: 24px; color: black">
                      <!-- Add username here -->{{user.username | title}}
                    </h6>
                    <p style="font-size: 14px; color: black">
                      <!-- Add bio here -->
                      {{user.profile.bio}}
                    </p>
                    <i
                      class="mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"
                    ></i>
                    <div style="margin-top: 10px">
                      <button class="btn btn-primary" id="logout-btn">
                        <a
                          id="fa"
                          href="{% url 'profile_update' %}"
                          style="color: white; text-decoration: none"
                          >Update Profile</a
                        >
                      </button>
                    </div>
                  </div>
                </div>
                <div class="col-sm-8">
                  <div class="card-block">
                    <h6 class="m-b-20 p-b-5 b-b-default f-w-600">
                      Information
                    </h6>
                    <div class="row">
                      <div class="col-sm-6">
                        <p class="m-b-10 f-w-600">Email</p>
                        <h6 class="text-muted f-w-400">
                          <!-- Add email here -->
                          {{user.email}}
                        </h6>
                      </div>
                      <div class="col-sm-6">
                        <p class="m-b-10 f-w-600">Phone</p>
                        <h6 class="text-muted f-w-400">
                          <!-- Add phone here -->{{user.profile.phone}}
                        </h6>
                      </div>
                    </div>
                    <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">
                      Projects
                    </h6>
                    <div class="row">
                      <div class="col-sm-6">
                        <p class="m-b-10 f-w-600">Recent</p>
                        <h6 class="text-muted f-w-400">
                          <a href="#">Project1</a>
                        </h6>
                      </div>
                      <div class="col-sm-6">
                        <p class="m-b-10 f-w-600">Most Viewed</p>
                        <h6 class="text-muted f-w-400">
                          <a href="#">Project2</a>
                        </h6>
                      </div>
                      <div style="margin-top: 55px">
                        <button class="btn btn-secondary" id="logout-btn">
                          <a
                            id="fa"
                            href=""
                            style="color: white; text-decoration: none"
                            >Ask Question</a
                          >
                        </button>
                        <button class="btn btn-outline-primary" id="logout-btn">
                          <a
                            id="fa"
                            href=""
                            style="color: rgb(0, 0, 0); text-decoration: none"
                            >View Questions</a
                          >
                        </button>
                      </div>
                    </div>

                    <ul class="social-link list-unstyled m-t-40 m-b-10">
                      <li>
                        <a
                          href="#!"
                          data-toggle="tooltip"
                          data-placement="bottom"
                          title=""
                          data-original-title="facebook"
                          data-abc="true"
                          ><i
                            class="mdi mdi-facebook feather icon-facebook facebook"
                            aria-hidden="true"
                          ></i
                        ></a>
                      </li>
                      <li>
                        <a
                          href="#!"
                          data-toggle="tooltip"
                          data-placement="bottom"
                          title=""
                          data-original-title="twitter"
                          data-abc="true"
                          ><i
                            class="mdi mdi-twitter feather icon-twitter twitter"
                            aria-hidden="true"
                          ></i
                        ></a>
                      </li>
                      <li>
                        <a
                          href="#!"
                          data-toggle="tooltip"
                          data-placement="bottom"
                          title=""
                          data-original-title="instagram"
                          data-abc="true"
                          ><i
                            class="mdi mdi-instagram feather icon-instagram instagram"
                            aria-hidden="true"
                          ></i
                        ></a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <script>
      feather.replace();
    </script>
  </body>
</html>
{% endblock content %}